# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

try:
    from . import engine_client_pb2 as engine__client__pb2
except ImportError:
    import engine_client_pb2 as engine__client__pb2

GRPC_GENERATED_VERSION = "1.60.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = False

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in engine_client_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EngineServiceStub:
    """Service exposed by the Python Worker Daemon for vllm-router"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStream = channel.unary_stream(
            "/vllm.engine.v1.EngineService/GenerateStream",
            request_serializer=engine__client__pb2.GenerateRequest.SerializeToString,
            response_deserializer=engine__client__pb2.GenerateStreamResponse.FromString,
            _registered_method=True,
        )
        self.Generate = channel.unary_unary(
            "/vllm.engine.v1.EngineService/Generate",
            request_serializer=engine__client__pb2.GenerateRequest.SerializeToString,
            response_deserializer=engine__client__pb2.GenerateResponse.FromString,
            _registered_method=True,
        )
        self.GetModelInfo = channel.unary_unary(
            "/vllm.engine.v1.EngineService/GetModelInfo",
            request_serializer=engine__client__pb2.ModelInfoRequest.SerializeToString,
            response_deserializer=engine__client__pb2.ModelInfoResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/vllm.engine.v1.EngineService/HealthCheck",
            request_serializer=engine__client__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=engine__client__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.StartProfile = channel.unary_unary(
            "/vllm.engine.v1.EngineService/StartProfile",
            request_serializer=engine__client__pb2.EmptyRequest.SerializeToString,
            response_deserializer=engine__client__pb2.AdminResponse.FromString,
            _registered_method=True,
        )
        self.StopProfile = channel.unary_unary(
            "/vllm.engine.v1.EngineService/StopProfile",
            request_serializer=engine__client__pb2.EmptyRequest.SerializeToString,
            response_deserializer=engine__client__pb2.AdminResponse.FromString,
            _registered_method=True,
        )
        self.ResetPrefixCache = channel.unary_unary(
            "/vllm.engine.v1.EngineService/ResetPrefixCache",
            request_serializer=engine__client__pb2.EmptyRequest.SerializeToString,
            response_deserializer=engine__client__pb2.AdminResponse.FromString,
            _registered_method=True,
        )


class EngineServiceServicer:
    """Service exposed by the Python Worker Daemon for vllm-router"""

    def GenerateStream(self, request, context):
        """Bi-directional / Server streaming for token generation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Generate(self, request, context):
        """Unary generation (returns complete output after finishing)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Model and backend capability discovery"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health and readiness probing"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartProfile(self, request, context):
        """Cluster admin and profiling controls"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetPrefixCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateStream": grpc.unary_stream_rpc_method_handler(
            servicer.GenerateStream,
            request_deserializer=engine__client__pb2.GenerateRequest.FromString,
            response_serializer=engine__client__pb2.GenerateStreamResponse.SerializeToString,
        ),
        "Generate": grpc.unary_unary_rpc_method_handler(
            servicer.Generate,
            request_deserializer=engine__client__pb2.GenerateRequest.FromString,
            response_serializer=engine__client__pb2.GenerateResponse.SerializeToString,
        ),
        "GetModelInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
            request_deserializer=engine__client__pb2.ModelInfoRequest.FromString,
            response_serializer=engine__client__pb2.ModelInfoResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=engine__client__pb2.HealthCheckRequest.FromString,
            response_serializer=engine__client__pb2.HealthCheckResponse.SerializeToString,
        ),
        "StartProfile": grpc.unary_unary_rpc_method_handler(
            servicer.StartProfile,
            request_deserializer=engine__client__pb2.EmptyRequest.FromString,
            response_serializer=engine__client__pb2.AdminResponse.SerializeToString,
        ),
        "StopProfile": grpc.unary_unary_rpc_method_handler(
            servicer.StopProfile,
            request_deserializer=engine__client__pb2.EmptyRequest.FromString,
            response_serializer=engine__client__pb2.AdminResponse.SerializeToString,
        ),
        "ResetPrefixCache": grpc.unary_unary_rpc_method_handler(
            servicer.ResetPrefixCache,
            request_deserializer=engine__client__pb2.EmptyRequest.FromString,
            response_serializer=engine__client__pb2.AdminResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "vllm.engine.v1.EngineService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "vllm.engine.v1.EngineService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EngineService:
    """Service exposed by the Python Worker Daemon for vllm-router"""

    @staticmethod
    def GenerateStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/vllm.engine.v1.EngineService/GenerateStream",
            engine__client__pb2.GenerateRequest.SerializeToString,
            engine__client__pb2.GenerateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Generate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/Generate",
            engine__client__pb2.GenerateRequest.SerializeToString,
            engine__client__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetModelInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/GetModelInfo",
            engine__client__pb2.ModelInfoRequest.SerializeToString,
            engine__client__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/HealthCheck",
            engine__client__pb2.HealthCheckRequest.SerializeToString,
            engine__client__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/StartProfile",
            engine__client__pb2.EmptyRequest.SerializeToString,
            engine__client__pb2.AdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/StopProfile",
            engine__client__pb2.EmptyRequest.SerializeToString,
            engine__client__pb2.AdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetPrefixCache(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vllm.engine.v1.EngineService/ResetPrefixCache",
            engine__client__pb2.EmptyRequest.SerializeToString,
            engine__client__pb2.AdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
